import type { CapacitorConfig } from '@capacitor/cli'

const config: CapacitorConfig = {
  appId: 'com.iqcapture.mobile',
  appName: 'IQ:capture',
  webDir: 'out',
  server: {
    // During development, point to Next.js dev server
    // url: 'http://localhost:3119',
    // cleartext: true,
  },
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/CapacitorDatabase',
      iosIsEncryption: false,
      androidIsEncryption: false,
    },
  },
  // Deep linking configuration
  // iOS: Add Associated Domains entitlement in Xcode (applinks:app.iqcapture.app)
  // Android: intent-filter entries are auto-generated by Capacitor
  //
  // Supported deep link patterns:
  //   iqcapture://auth/reset-password?email=...&code=...
  //   https://app.iqcapture.app/auth/reset-password?email=...&code=...
  //   https://app.iqcapture.app/auth/verify-email?email=...&code=...
}

export default config
